---
kind: Namespace
apiVersion: v1
metadata:
  name: blog
  labels:
    name: blog
---
apiVersion: v1
kind: Service
metadata:
  name: blog
  namespace: blog
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: tcp-80
      port: 80
      targetPort: 80
    - protocol: TCP
      name: tcp-443
      port: 443
      targetPort: 80
  selector:
    app.kubernetes.io/name: blog
    app.kubernetes.io/part-of: blog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  namespace: blog
  labels:
    app.kubernetes.io/name: blog
    app.kubernetes.io/part-of: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: blog
      app.kubernetes.io/part-of: blog
  template:
    metadata:
      labels:
        app.kubernetes.io/name: blog
        app.kubernetes.io/part-of: blog
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: web-pool
      containers:
        - name: "blog"
          image: gcr.io/tk8-cluster/blog:latest
          imagePullPolicy: "Always"
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          # livenessProbe:
          #   failureThreshold: 3
          #   httpGet:
          #     path: /health
          #     port: 80
          #     scheme: HTTP
          #   initialDelaySeconds: 10
          #   periodSeconds: 10
          #   successThreshold: 1
          #   timeoutSeconds: 1
          # readinessProbe:
          #   failureThreshold: 3
          #   httpGet:
          #     path: /health
          #     port: 80
          #     scheme: HTTP
          #   periodSeconds: 10
          #   successThreshold: 1
          #   timeoutSeconds: 1
