baseurl = "/"
languageCode = "en-us"
title = "T++"
enableInlineShortcodes = true
RelativeURLs=true
paginate = 3

theme = "casper3"

[params]
  twitter = "https://twitter.com/kyeotic"
  github = "https://github.com/kyeotic"
  description = "T++"
  mainSections = ["post"]
  # pygmentsCodeFences = true
  # pygmentsStyle="monokai"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"