version: '3.7'
services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile.local
    command: hugo server -D --watch=true --bind 0.0.0.0
    ports:
      - 1313:1313
    volumes:
      - ../blog:/web